### ISSUE TITLE
How to switch to CDC mode ?

### ISSUE THREAD

**Issue by galaxy001** [hypoxic/GoPro-Research#1]
In your tear down [blog](https://gethypoxic.com/blogs/technical/gopro-hero8-teardown), you said: 
> sending the USB Vendor extension 0x9002 and then send a file named 'MTP_TO_CDC.TXT' in the same connection, USB will switch to CDC mode.

Would you tell me how to achieve this with a Linux PC ?

**Comment by hypoxic** [comment]
Sorry, I hacked up libmtp to perform this task and the code is definitely not ready for release. If I were to do it today, I would just set a breakpoint (or use Frida) on the GoPro desktop app during the erase file command. It executes the 0x9002 extension. From that point just copy a blank file named 'MTP_TO_CDC.TXT' onto the volume and it should enable cdc. I've seen python libraries for fuzzing MTP but have not explored it much.

**Comment by Novex** [comment]
@galaxy001 did you ever get this working? I'm trying to also do this and I can successfully unlock the sd card and create the MTP_TO_CDC.TXT file but nothing seems to happen afterwards.

**Comment by hypoxic** [comment]
Seb,

I have. You may have to do a USB re-enumeration for it to take effect.
Also, I would try one of the earlier firmwares as I'm not sure if they took
this out or not.
